0x05-python-exceptions for faustina
